### ISSUE TITLE
Access denied for slides

### ISSUE THREAD

**Issue by lucasgrjn** [SiEPIC/openEBL-2024-02#11]
Hi,

It is currently impossible to access the [slides](https://docs.google.com/presentation/d/18B8UAUWxal7vW1-bIIp5o7Mb6nLZ9Ep64zdLF2bcjPQ).
Can you open them?

Thanks!

**Comment by lukasc-ubc** [comment]
Hi @lucasgrjn 
We are getting this ready for the next tape-out and the edX course that starts in January.  I will release the slides when they are ready.
regards
Lukas

**Comment by lucasgrjn** [comment]
@lukasc-ubc  thanks for the response!

**Comment by lukasc-ubc** [comment]
feel free to try the submission system if you are already familiar with the process.

**Comment by lucasgrjn** [comment]
I made one during the course I took on 2017. And I will definitely do a new one(s) for your next tapeout(s) :)

Just to be sure, the chip processed will only be passive or is it possible to include some heater on top of it (as pointed on the OpenEBL website)?

**Comment by lukasc-ubc** [comment]
We are adding additional fabrication runs for returning students in the course, including thermo-optics.  It will be a separate submission repository.  This one is for the passives run.

**Comment by lucasgrjn** [comment]
Really glad to read that!

I am looking forward to see the future tapeouts list!
