### ISSUE TITLE
i have error on run time in python

### ISSUE THREAD

**Issue by behroozmahtabi** [SiEPIC/openEBL-2024-02#308]
from sqlalchemy import create_engine, String, TEXT, Integer, Column
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import Session, sessionmaker

engen = create_engine ("sqlite:///mydb.db", echo=True)
Base = declarative_base()
Sessions = sessionmaker(bind=engen)
session = Session()

after run it show below message

E:\python project\Tk2\db.py:8: MovedIn20Warning: The ``declarative_base()`` function is now available as sqlalchemy.orm.declarative_base(). (deprecated since: 2.0) (Background on SQLAlchemy 2.0 at: https://sqlalche.me/e/b8d9)
  Base = declarative_base()

**Comment by shorya1853** [comment]
Update the import statement:

`from sqlalchemy.orm import declarative_base`

**Comment by behroozmahtabi** [comment]
thank you but how can i update it because i am junior in python?
