### ISSUE TITLE
Do not see GDS files in submission

### ISSUE THREAD

**Issue by pwflanigan** [SiEPIC/openEBL-2024-02#313]
Prof. Chrostowski,

Back in February, I submitted my GDS layout files on the old version of https://siepic.ca/openebl/, but I don't see them anywhere in this Github repository. Is there a way that I can check that were included in this run? (Also, is the data available yet? I didn't see it on this page). If they're not, I can just wait until the next fabrication deadline in May.

Best,

-Patrick Flanigan

**Comment by lukasc-ubc** [comment]
Hi Patrick,

The submission for the 2024-02 run was via this GitHub page, as described in the Readme file. The measurement data is also linked at the bottom.

Can you please submit your designs for the next run, on GitHub in the 2024-05 repo?

Thank you
